[package]
name = "kapanis"
version = "1.1.0"
description = "Sakin ve düşük kaynak tüketimli Windows kapatma ve alarm zamanlayıcısı."
authors = ["kapanış."]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "kapanis_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
base64 = "0.22"

[dependencies]
local-ip-address = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
socket2 = "0.5"
tauri = { version = "2", features = ["tray-icon", "unstable"] }
tauri-plugin-autostart = "2"
tauri-plugin-notification = "2"
tauri-plugin-single-instance = "2"
tiny_http = "0.12"
native-tls = "0.2"
ureq = { version = "2.10", features = ["native-tls"] }
uuid = { version = "1", features = ["v4"] }
window-vibrancy = "0.6"
notify = "6.1"
rfd = "0.15"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61.3", features = ["Foundation", "Media_Control"] }
