import assert from 'node:assert/strict'
import { applyTabProjectionState, canStartNativeRestore, closeTabState, EMPTY_BROWSER_STATE, lastPlayingMedia, migrateBrowserState, nativeNavigationAction, nativeRestoreTasks, nativeViewAction, openTabState, prepareNewTabNavigation, resolveOptimisticClose, selectTabState, serializeBrowserState, validateTabId, type BrowserState } from './browserState'
import { faviconForBrowserUrl } from './browserData'

const tabs = ['a', 'b', 'c'].map((id) => ({ id, url: `https://${id}.example`, title: id, favicon: null, loading: false, canGoBack: false, canGoForward: false, error: null }))
let state: BrowserState = { ...EMPTY_BROWSER_STATE, tabs, activeTabId: 'b', mediaByTabId: { b: { tabId: 'b', playing: true, lastPlayingAt: 2 }, a: { tabId: 'a', playing: true, lastPlayingAt: 1 } } }
state = closeTabState(state, 'b')
assert.equal(state.activeTabId, 'c')
assert.equal(lastPlayingMedia(state.mediaByTabId)?.tabId, 'a')
assert.equal(closeTabState(state, 'missing'), state)
assert.equal(closeTabState({ ...state, tabs: [tabs[0]], activeTabId: 'a' }, 'a').activeTabId, null)
assert.ok(validateTabId('tab_1')); assert.ok(!validateTabId('../unsafe'))
const migrated = migrateBrowserState([{ id: 'good', url: 'https://example.com', title: '' }, { id: '../bad', url: 'https://bad.example', title: 'bad' }, { id: 'alsoBad', url: 'file:///unsafe', title: 'bad' }], 'good')
assert.equal(migrated.tabs.length, 1)
assert.equal(migrated.tabs[0].favicon, 'https://example.com/favicon.ico')
assert.equal(serializeBrowserState(closeTabState(migrated, 'good')).activeTabId, null)
const optimistic = closeTabState({ ...EMPTY_BROWSER_STATE, tabs: [tabs[0]], activeTabId: 'a', mediaByTabId: {} }, 'a')
assert.equal(resolveOptimisticClose({ ...EMPTY_BROWSER_STATE, tabs: [tabs[0]], activeTabId: 'a', mediaByTabId: {} }, optimistic, false).tabs[0].id, 'a')
const stablePlaying = { a: { tabId: 'a', playing: true, lastPlayingAt: 10 }, b: { tabId: 'b', playing: true, lastPlayingAt: 20 } }
assert.equal(lastPlayingMedia(stablePlaying)?.tabId, 'b')
assert.equal(lastPlayingMedia({ ...stablePlaying, a: { ...stablePlaying.a, title: 'poll update' } })?.tabId, 'b')
assert.equal(lastPlayingMedia({ ...stablePlaying, b: { ...stablePlaying.b, playing: false } })?.tabId, 'a')
const opened = openTabState(EMPTY_BROWSER_STATE, tabs[0])
assert.equal(opened.tabs.length, 1)
assert.equal(opened.activeTabId, 'a')
assert.equal(opened.tabs[0].url, 'https://a.example')
const blankTab = { ...tabs[0], id: 'blank', url: null, title: 'Yeni Sekme' }
const blankSelected = openTabState({ ...EMPTY_BROWSER_STATE, tabs: [tabs[0]], activeTabId: 'a', mediaByTabId: {} }, blankTab)
assert.deepEqual(nativeViewAction(blankSelected), { type: 'deactivate' })
assert.deepEqual(nativeViewAction(selectTabState(blankSelected, 'a')), { type: 'activate', tabId: 'a' })
assert.deepEqual(nativeRestoreTasks(blankSelected), [{ tabId: 'a', url: 'https://a.example' }])
assert.deepEqual(nativeRestoreTasks({ ...blankSelected, tabs: [...blankSelected.tabs, { ...tabs[0] }] }), [{ tabId: 'a', url: 'https://a.example' }])
assert.equal(nativeNavigationAction(tabs[0], false), 'create')
assert.equal(nativeNavigationAction(tabs[0], true), 'navigate')
assert.equal(canStartNativeRestore(false, true, false), false)
assert.equal(canStartNativeRestore(true, false, false), false)
assert.equal(canStartNativeRestore(true, true, false), true)
assert.equal(canStartNativeRestore(true, true, true), false)
const prepared = prepareNewTabNavigation(EMPTY_BROWSER_STATE, tabs[0], 'https://example.com')
assert.equal(prepared.state.tabs.length, 1)
assert.equal(prepared.tabId, 'a')
assert.equal(prepared.url, 'https://example.com')
const nativeCreated = applyTabProjectionState(prepared.state, { id: 'a', url: 'https://example.com', title: 'Example Domain', favicon: 'https://example.com/favicon.ico', loading: true, canGoBack: false, canGoForward: false, error: null, label: 'browser-a' })
assert.equal(nativeCreated.tabs.length, 1)
assert.equal(nativeCreated.tabs[0].url, 'https://example.com')
assert.equal(nativeCreated.tabs[0].title, 'Example Domain')
assert.equal(faviconForBrowserUrl('https://example.com/path'), 'https://example.com/favicon.ico')
assert.equal(faviconForBrowserUrl('file:///nope'), null)
for (let index = 0; index < 30; index += 1) state = closeTabState({ ...EMPTY_BROWSER_STATE, tabs: [tabs[0]], activeTabId: 'a', mediaByTabId: { a: { tabId: 'a', playing: true, lastPlayingAt: index } } }, 'a')
assert.deepEqual(state, EMPTY_BROWSER_STATE)
console.log('browser lifecycle state tests passed')
