import type { TranslationRow } from '../types'

export const POWER_TRANSLATIONS: Readonly<Record<string, TranslationRow>> = {
  'Güç sayacı': ['Power timer', 'Energie-Timer', 'Minuterie d’alimentation', 'Temporizador de energía', 'Timer alimentazione', 'Temporizador de energia', 'Таймер питания', 'مؤقت الطاقة', '电源计时器', '電源タイマー', '전원 타이머'],
  'Hazır süreler': ['Quick durations', 'Schnellzeiten', 'Durées rapides', 'Duraciones rápidas', 'Durate rapide', 'Durações rápidas', 'Готовые интервалы', 'مدد سريعة', '快捷时长', 'クイック時間', '빠른 시간 설정'],
  'İptal ediliyor…': ['Cancelling…', 'Wird abgebrochen…', 'Annulation…', 'Cancelando…', 'Annullamento…', 'Cancelando…', 'Отмена…', 'جارٍ الإلغاء…', '正在取消…', 'キャンセル中…', '취소 중…'],
  'Kapatmayı planla': ['Schedule shutdown', 'Herunterfahren planen', 'Programmer l’arrêt', 'Programar apagado', 'Programma spegnimento', 'Agendar desligamento', 'Запланировать выключение', 'جدولة إيقاف التشغيل', '计划关机', 'シャットダウンを予約', '종료 예약'],
  'Pencere kapansa da Windows sayacı çalışır.': ['The Windows timer keeps running even when the window is closed.', 'Der Windows-Timer läuft weiter, auch wenn das Fenster geschlossen wird.', 'Le minuteur Windows continue de fonctionner même si la fenêtre est fermée.', 'El temporizador de Windows sigue funcionando aunque se cierre la ventana.', 'Il timer di Windows continua a funzionare anche se la finestra viene chiusa.', 'O temporizador do Windows continua funcionando mesmo com a janela fechada.', 'Таймер Windows продолжает работать даже после закрытия окна.', 'يستمر مؤقت Windows بالعمل حتى عند إغلاق النافذة.', '即使关闭窗口，Windows 计时器仍会继续运行。', 'ウィンドウを閉じても Windows タイマーは動作し続けます。', '창을 닫아도 Windows 타이머는 계속 실행됩니다.'],
  'Planı iptal et': ['Cancel plan', 'Plan abbrechen', 'Annuler le plan', 'Cancelar plan', 'Annulla piano', 'Cancelar plano', 'Отменить план', 'إلغاء الخطة', '取消计划', 'プランをキャンセル', '계획 취소'],
  '{action} planlandı': ['{action} scheduled', '{action} geplant', '{action} programmé', '{action} programado', '{action} programmato', '{action} agendado', '{action} запланировано', 'تمت جدولة {action}', '已计划{action}', '{action}を予約しました', '{action} 예약됨'],
  'Planlanıyor…': ['Scheduling…', 'Wird geplant…', 'Programmation…', 'Programando…', 'Programmazione…', 'Agendando…', 'Планирование…', 'جارٍ الجدولة…', '正在计划…', '予約中…', '예약 중…'],
  'Süre': ['Duration', 'Dauer', 'Durée', 'Duración', 'Durata', 'Duração', 'Длительность', 'المدة', '时长', '時間', '시간'],
  'Süre dolunca': ['When time expires', 'Wenn die Zeit abläuft', 'À la fin du délai', 'Cuando termine el tiempo', 'Allo scadere del tempo', 'Quando o tempo acabar', 'По истечении времени', 'عند انتهاء المدة', '时间到后', '時間になったら', '시간이 끝나면'],
  'Süre dolunca seçilen Windows işlemi uygulanır.': ['The selected Windows action runs when the timer expires.', 'Die ausgewählte Windows-Aktion wird ausgeführt, wenn der Timer abläuft.', 'L’action Windows sélectionnée s’exécute à la fin du minuteur.', 'La acción de Windows seleccionada se ejecuta al terminar el temporizador.', 'L’azione Windows selezionata viene eseguita allo scadere del timer.', 'A ação do Windows selecionada será executada quando o temporizador terminar.', 'Выбранное действие Windows выполнится по истечении таймера.', 'يتم تنفيذ إجراء Windows المحدد عند انتهاء المؤقت.', '计时结束后将执行所选的 Windows 操作。', 'タイマー終了時に選択した Windows 操作を実行します。', '타이머가 끝나면 선택한 Windows 작업이 실행됩니다.'],
  'Tepside çalışır': ['Runs in tray', 'Läuft im Tray', 'Fonctionne dans la zone de notification', 'Funciona en la bandeja', 'Funziona nell’area di notifica', 'Funciona na bandeja', 'Работает в трее', 'يعمل في شريط النظام', '在托盘中运行', 'トレイで動作', '트레이에서 실행'],
  'Windows ile açılır': ['Starts with Windows', 'Startet mit Windows', 'Démarre avec Windows', 'Se inicia con Windows', 'Si avvia con Windows', 'Inicia com o Windows', 'Запускается вместе с Windows', 'يبدأ مع Windows', '随 Windows 启动', 'Windows と同時に起動', 'Windows와 함께 시작'],
  'Windows işlemi': ['Windows action', 'Windows-Aktion', 'Action Windows', 'Acción de Windows', 'Azione Windows', 'Ação do Windows', 'Действие Windows', 'إجراء Windows', 'Windows 操作', 'Windows 操作', 'Windows 작업'],
  'Windows planı aktif': ['Windows plan active', 'Windows-Plan aktiv', 'Plan Windows actif', 'Plan de Windows activo', 'Piano Windows attivo', 'Plano do Windows ativo', 'План Windows активен', 'خطة Windows نشطة', 'Windows 计划已启用', 'Windows プラン有効', 'Windows 계획 활성화'],
  'Yeniden başlat': ['Restart', 'Neu starten', 'Redémarrer', 'Reiniciar', 'Riavvia', 'Reiniciar', 'Перезагрузить', 'إعادة التشغيل', '重启', '再起動', '다시 시작'],
  'Yeniden başlatma': ['Restart', 'Neustart', 'Redémarrage', 'Reinicio', 'Riavvio', 'Reinicialização', 'Перезагрузка', 'إعادة التشغيل', '重启', '再起動', '다시 시작'],
  'Yeniden başlatmayı planla': ['Schedule restart', 'Neustart planen', 'Programmer le redémarrage', 'Programar reinicio', 'Programma riavvio', 'Agendar reinicialização', 'Запланировать перезагрузку', 'جدولة إعادة التشغيل', '计划重启', '再起動を予約', '다시 시작 예약'],
  'Dakika': ['Minute', 'Minute', 'Minute', 'Minuto', 'Minuto', 'Minuto', 'Минута', 'دقيقة', '分钟', '分', '분'],
  'Saniye': ['Second', 'Sekunde', 'Seconde', 'Segundo', 'Secondo', 'Segundo', 'Секунда', 'ثانية', '秒', '秒', '초'],
}
